#!/usr/bin/env python3
from cardmanager import CardManager
import click


@click.group()
def cli():
    pass

@cli.command()
@click.argument("path")
@click.option("-i","--in-place", default=False)
@click.option("-o","--output", default=None)
def format(path:str, in_place:bool, output:str):
    if not (in_place or output) or (in_place and output):
        raise RuntimeError("Please provide *either* -i *or* -o!")

    if in_place:
        outfile = path
    if output:
        outfile = output
    cm = CardManager(path, ".")
    cm.write(outfile)

if __name__ == "__main__":
    cli()